package ru.lavafrai.maiapp.theme

import androidx.compose.ui.graphics.Color

//generated by https://materialkolor.com
//Color palette was taken here: https://coolors.co/palette/e63946-f1faee-a8dadc-457b9d-1d3557

internal val MaiColor = Color(0xff377cfd)
internal val LinkColor = Color(0xff148fe6)