FROM node:20-alpine AS build

WORKDIR /opt/app
RUN apk add --no-cache python3 make g++ autoconf automake libtool nasm pkgconfig zlib-dev
COPY landing/package.json landing/package-lock.json* ./

RUN npm install
COPY landing/ ./

RUN npm run build

FROM nginx:alpine

COPY landing/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /opt/app/dist/ /usr/share/nginx/html