services:
  server2:
    image: ghcr.io/lavafrai/maiapp/maiserver:latest
    container_name: mai-server2
    restart: unless-stopped
    expose:
      - "80"
    healthcheck:
      test: curl -sS http://127.0.0.1/groups || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  landing:
    image: ghcr.io/lavafrai/maiapp/maiapp-landing:latest
    container_name: mai-landing
    restart: unless-stopped
    expose:
      - "80"
    healthcheck:
      test: curl -sS http://127.0.0.1 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  nginx-internal:
    image: nginx:alpine
    container_name: mai-nginx-internal
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - ./server-configs/nginx-internal/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server2
      - landing
    healthcheck:
      test: curl -sS https://maiapp.lavafrai.ru/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  caddy-external:
    build:
      context: server-configs/caddy-external
      dockerfile: Dockerfile
    container_name: mai-caddy-external
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./server-configs/caddy-external/Caddyfile:/etc/caddy/Caddyfile
      - caddy-usage-data:/usage-data
    depends_on:
      - nginx-internal

volumes:
  caddy-usage-data:
