global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'maiapp'
    scrape_interval: 5s
    static_configs:
      - scheme: https
      - path: /metrics
      - targets: ['caddy:80']
