name: Build and Push Images

on:
  push:
    branches: [ "master" ]
    paths:
      - 'server/**'
      - 'Dockerfile.server'
      - 'landing/**'
      - 'Dockerfile.landing'
      - 'shared/**'
      - 'models/**'
      - 'network/**'
      - 'gradle/libs.versions.toml'
      - '.github/workflows/build-and-push.yml'
  workflow_dispatch:

jobs:
  build_server_image:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common-build-setup
        with:
          java-version: '17'
          secrets-properties: ${{ secrets.SECRETS_PROPERTIES }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Server Image
        run: |
          docker build -f Dockerfile.server . --tag ghcr.io/${{ github.repository }}/maiserver:latest
          docker push ghcr.io/${{ github.repository }}/maiserver:latest

  build_landing_image:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common-build-setup
        with:
          java-version: '17'
          secrets-properties: ${{ secrets.SECRETS_PROPERTIES }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Landing Image
        run: |
          docker build -f Dockerfile.landing . --tag ghcr.io/${{ github.repository }}/maiapp-landing:latest
          docker push ghcr.io/${{ github.repository }}/maiapp-landing:latest