name: Build Snapshot

on:
    push:
        branches: [ "master" ]
        paths:
            - 'composeApp/**'
            - 'models/**'
            - 'shared/**'
            - 'gradle/libs.versions.toml'
    workflow_dispatch:

env:
    ANDROID_KEYSTORE: "../android.keystore"
    ANDROID_KEYSTORE_KEY: ${{ secrets.android_key_alias }}
    ANDROID_KEYSTORE_KEY_PASSWORD: ${{ secrets.android_key_password }}
    ANDROID_KEYSTORE_PASSWORD: ${{ secrets.android_keystore_password }}


jobs:
    build_android:
        name: Build Android
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  distribution: 'zulu'
                  java-version: '17'

            - name: Allow ro run Gradle
              run: chmod +x gradlew

            - name: Decode keystore
              uses: akiojin/decode-base64-github-action@v0.1.0
              with:
                  base64: ${{ secrets.ANDROID_KEYSTORE_B64 }}
                  output-path: '/home/runner/work/maiapp/maiapp/android.keystore'

            - name: Build with Gradle
              run: ./gradlew :composeApp:assemble

            - name: Rename APK
              run: mv composeApp/build/outputs/apk/release/*.apk composeApp/build/outputs/apk/release/maiapp-${timestamp}.apk

            - name: Upload Android artifact
              uses: actions/upload-artifact@v4
              with:
                  name: android-artifact
                  path: composeApp/build/outputs/apk/release/*.apk

    build_web:
        name: Build WEB
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  distribution: 'graalvm'
                  java-version: '21'

            - name: Allow ro run Gradle
              run: chmod +x gradlew

            - name: Build with Gradle
              run: ./gradlew :composeApp:wasmJsBrowserDistribution

            - name: Upload WEB artifact
              uses: actions/upload-artifact@v4
              with:
                  name: web-artifact
                  path: composeApp/build/dist/wasmJs/productionExecutable

            - name: Upload pages artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  name: pages-artifact
                  path: composeApp/build/dist/wasmJs/productionExecutable

    build_msi:
        name: Build MSI
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up JDK 11
              uses: actions/setup-java@v4
              with:
                    distribution: 'graalvm'
                    java-version: '21'

            - name: Build with Gradle
              run: ./gradlew :composeApp:packageMsi

            - name: Upload MSI artifact
              uses: actions/upload-artifact@v4
              with:
                    name: msi-artifact
                    path: composeApp\build\compose\binaries\main\msi\*

    build_deb:
        name: Build Debian
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up JDK 11
              uses: actions/setup-java@v4
              with:
                  distribution: 'graalvm'
                  java-version: '21'

            - name: Allow ro run Gradle
              run: chmod +x gradlew

            - name: Build with Gradle
              run: ./gradlew :composeApp:packageDeb

            - name: Upload DEB artifact
              uses: actions/upload-artifact@v4
              with:
                  name: deb-artifact
                  path: composeApp/build/compose/binaries/main/deb/*

    build_ios:
        name: Build iOS
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  distribution: 'graalvm'
                  java-version: '21'

            - uses: yukiarrr/ios-build-action@v1.12.0
              with:
                configuration: Release
                project-path: 'iosApp/iosApp.xcodeproj'
                workspace-path: 'iosApp/iosApp.xcodeproj/iosApp.xcworkspace'
                p12-base64: ${{ secrets.APPLE_P12_KEYSTORE_B64 }}
                mobileprovision-base64: ${{ secrets.APPLE_MOBILEPROVISION_B64 }}
                code-signing-identity: ${{ secrets.APPLE_CODE_SIGNING_IDENTITY }}
                team-id: ${{ secrets.APPLE_TEAM_ID }}
                certificate-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}

