name: Build Server

on:
    push:
        branches: [ "master" ]
        paths:
            - 'composeApp/**'
            - 'models/**'
            - 'shared/**'
    workflow_dispatch:

jobs:
    build_image_and_push:
        permissions:
            packages: write
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: 'Build Inventory Image'
          run: |
              docker build -f Dockerfile.server . --tag ghcr.io/${{ github.actor }}/maiserver:latest
              docker push ghcr.io/${{ github.actor }}/maiserver:latest

