name: Build KMP iOS App (maiapp)

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    env:
      SCHEME_NAME: iosApp
      WORKSPACE_PATH: iosApp/iosApp.xcodeproj/project.xcworkspace
      EXPORT_METHOD: app-store
      OUTPUT_DIR_IOS: iosApp/actions
      ARCHIVE_NAME: maiapp.xcarchive

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup common build environment
        uses: ./.github/actions/common-build-setup
        with:
          java-version: '17'
          secrets-properties: ${{ secrets.SECRETS_PROPERTIES }}

      - name: Set up Ruby for CocoaPods
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Cache CocoaPods dependencies
        uses: actions/cache@v4
        with:
          path: iosApp/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('iosApp/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install CocoaPods dependencies
        run: |
          cd iosApp
          pod install --repo-update

      # --- Диагностика настроек сборки (Показываем ВСЕ настройки) ---
      - name: Show Resolved Build Settings for Release
        run: |
          echo "--- Dumping ALL Resolved Build Settings for Release ---"
          cd iosApp
          xcodebuild -workspace iosApp.xcodeproj/project.xcworkspace \
                     -scheme iosApp \
                     -sdk iphoneos \
                     -configuration Release \
                     -showBuildSettings
          echo "--- End of ALL Build Settings Dump ---"

      # --- Настройка подписи кода ---
      - name: Import Apple Certificate
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.APPLE_P12_KEYSTORE_B64 }}
          p12-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}

      - name: Import Provisioning Profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "${{ env.APPLE_PROVISIONING_PROFILE_BASE64 }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/"${{ env.SCHEME_NAME }}_profile.mobileprovision"
        env:
          APPLE_PROVISIONING_PROFILE_BASE64: ${{ secrets.APPLE_MOBILEPROVISION_B64 }}

      # --- Проверка установленных профилей ---
      - name: List Installed Provisioning Profiles
        run: |
          echo "--- Listing Installed Provisioning Profiles ---"
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles
          echo "--- End of Profile Listing ---"

      # --- Создание ExportOptions.plist ---
      - name: Create ExportOptions.plist
        run: |
          cat << EOF > ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>${{ env.EXPORT_METHOD }}</string>
              <key>teamID</key>
              <string>${{ secrets.APPLE_TEAM_ID }}</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>ru.lavafrai.maiapp</key> <!-- Ваш Bundle ID -->
                  # ↓↓↓ ВОТ ЗДЕСЬ ↓↓↓
                  <string>maiapp-dist</string> <!-- Заменено на имя из Xcode -->
              </dict>
              <key>signingCertificate</key>
              <string>Apple Distribution</string>
              <key>uploadBitcode</key>
              <true/>
              <key>uploadSymbols</key>
              <true/>
          </dict>
          </plist>
          EOF
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          # !! ВАЖНО: Замените "ВАШЕ_ТОЧНОЕ_ИМЯ_PROVISIONING_PROFILE" в скрипте выше
          # на точное имя вашего Distribution профиля, которое вы указали в настройках Xcode

      # --- Сборка Архива (.xcarchive) ---
      - name: Build Xcode Archive
        run: |
          mkdir -p "${{ env.OUTPUT_DIR_IOS }}"
          # !! ДОБАВЛЕН ШАГ ОЧИСТКИ ПЕРЕД АРХИВАЦИЕЙ !!
          echo "--- Cleaning Xcode Build Folder ---"
          xcodebuild clean \
            -workspace "${{ env.WORKSPACE_PATH }}" \
            -scheme "${{ env.SCHEME_NAME }}" \
            -configuration Release
          echo "--- Starting Archive ---"
          # Используем ручную подпись, настроенную в проекте Xcode
          # Явно указываем Team ID
          xcodebuild archive \
            -workspace "${{ env.WORKSPACE_PATH }}" \
            -scheme "${{ env.SCHEME_NAME }}" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath "${{ env.OUTPUT_DIR_IOS }}/${{ env.ARCHIVE_NAME }}" \
            DEVELOPMENT_TEAM="${{ secrets.APPLE_TEAM_ID }}"

      # --- Экспорт IPA (.ipa) ---
      - name: Export IPA
        run: |
          # Проверяем существование ExportOptions.plist перед экспортом
          if [ ! -f ExportOptions.plist ]; then
            echo "ExportOptions.plist not found!"
            exit 1
          fi
          echo "--- Starting IPA Export ---"
          xcodebuild -exportArchive \
            -archivePath "${{ env.OUTPUT_DIR_IOS }}/${{ env.ARCHIVE_NAME }}" \
            -exportPath "${{ env.OUTPUT_DIR_IOS }}/" \
            -exportOptionsPlist ExportOptions.plist

      # --- Загрузка артефакта ---
      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-${{ github.run_number }}
          path: ${{ env.OUTPUT_DIR_IOS }}/${{ env.SCHEME_NAME }}.ipa
          retention-days: 7