on:
    workflow_run:
        workflows:
            - "Build MSI"
        types:
            - completed

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Download MSI artifact
              uses: actions/download-artifact@v2
              with:
                  name: msi-artifact
                  path: maiapp.msi

            - name: Publish MSI artifact
              run: du -h maiapp.msi
